name: Publish to PyPI

on:
  push:
    tags: ["v*.*.*"]

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash

jobs:
  checks:
    uses: ./.github/workflows/ci.yml

  publish:
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
      - run: uv build
      - run: uv publish
